version: '3.8'

services:
  server:
    container_name: fetish_talk-server
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./packages/server:/server
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      net1:
        ipv4_address: 192.168.10.10

  mysql:
    image: mysql:8.0
    container_name: fetish_talk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    networks:
      net1:
        ipv4_address: 192.168.10.20

networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
